spring.application.name=finance-backend
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=Vkiii@2004
spring.datasource.password=Vkiii@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


server.port=8080

